name: Deploy to Alwaysdata

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Dependencies (on GitHub Runner)
        run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress

      - name: Sync files to Alwaysdata
        uses: appleboy/rsync-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          target: "~/www"
          args: "-az --delete --exclude='.env' --exclude='storage/*.key'"

      - name: Post-deployment tasks
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/www
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force